### ISSUE TITLE
getResponse() function has empty body on links with raw files

### ISSUE THREAD

**Issue by faraazahmad** [hahnicity/go-wget#1]
for example: https://google.com works fine
but https://pastebin.com/raw/FLt4jxHJ or https://raw.githubusercontent.com/hahnicity/go-wget/master/gowget.go doesn't

**Comment by faraazahmad** [comment]
I'm assuming that's just because the code is about 6 years old, found some new code here https://golangcode.com/download-a-file-from-a-url/

**Comment by hahnicity** [comment]
Hello, thanks for taking interest in this project. I wrote it when I was new to Go and with a very old Go version. As such I will not be supporting this code in the future. Perhaps a more mature library will work better for you?
